---
:ems:
  :ems_dummy_provider:
    :blacklisted_event_names: []
    :event_handling:
      :event_groups:
        :power:
          :critical:
            - DUMMY_PROVIDER_instance_power_on
            - DUMMY_PROVIDER_instance_power_off
:ems_refresh:
  :dummy_provider:
    # Switches refresh to graph refresh on [Graph refresh only]
    :allow_targeted_refresh: true
    :inventory_collections:
      # Strategy for saving, another allowed is batch, doing batch SQL queries [Graph refresh only]
      :saver_strategy: batch
:http_proxy:
  :dummy_provider:
    :host:
    :password:
    :port:
    :user:
:workers:
  :ems_metrics_collector_worker_dummy_provider:
    :inherits_from: ems_metrics_collector_worker
  :ems_refresh_worker_dummy_provider:
    :inherits_from: ems_refresh_worker
  :event_catcher_dummy_provider:
    :inherits_from: event_catcher
    :poll: 20.seconds
